p8105_hw2_SC4934
================

``` r
library(tidyverse)
library(readxl)
```

# Problem 1

## import data

``` r
trans_ent = 
  read_csv(
    "data/chs03.csv",
    col_types = cols(Route8 = "c", Route9 = "c", Route10 = "c", Route11 = "c")) %>% 
  janitor::clean_names() %>% 
  select(
    line, station_name, station_latitude, station_longitude, 
    starts_with("route"), entry, exit_only, vending, entrance_type, 
    ada) %>% 
  mutate(entry = ifelse(entry == "YES", TRUE, FALSE))
```

``` r
skimr::skim(trans_ent)
```

## description:

the dataset `trans_ent` contains 1868 rows and 19 columns. There are 15
character, 2 logical, and 2 numeric variables. it includes variables:
line, station_name, station_latitude, station_longitude, all the
vairables that start with “route” (which are routes served), entry,
exit_only, vending, entrance_type, and ada. I used
`janitor::clean_names` to start the tidying process, which converts
column names to lower snake case. I also used `col_types` to convert
some columns to character format. I used `select` to select the
variables I wanted to include, and used `mutate` to convert entry
variable to logical type.

this data is not tidy!

``` r
trans_ent %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 465 × 2
    ##    station_name             line    
    ##    <chr>                    <chr>   
    ##  1 25th St                  4 Avenue
    ##  2 36th St                  4 Avenue
    ##  3 45th St                  4 Avenue
    ##  4 53rd St                  4 Avenue
    ##  5 59th St                  4 Avenue
    ##  6 77th St                  4 Avenue
    ##  7 86th St                  4 Avenue
    ##  8 95th St                  4 Avenue
    ##  9 9th St                   4 Avenue
    ## 10 Atlantic Av-Barclays Ctr 4 Avenue
    ## # … with 455 more rows
    ## # ℹ Use `print(n = ...)` to see more rows

After selecting only `station_name` and `line` and using the `distinct`
function to obtain all unique combinations, we can see that there are
465 distinct stations.

``` r
trans_ent %>% 
  filter(ada == TRUE) %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 84 × 2
    ##    station_name                   line           
    ##    <chr>                          <chr>          
    ##  1 Atlantic Av-Barclays Ctr       4 Avenue       
    ##  2 DeKalb Av                      4 Avenue       
    ##  3 Pacific St                     4 Avenue       
    ##  4 Grand Central                  42nd St Shuttle
    ##  5 34th St                        6 Avenue       
    ##  6 47-50th Sts Rockefeller Center 6 Avenue       
    ##  7 Church Av                      6 Avenue       
    ##  8 21st St                        63rd Street    
    ##  9 Lexington Av                   63rd Street    
    ## 10 Roosevelt Island               63rd Street    
    ## # … with 74 more rows
    ## # ℹ Use `print(n = ...)` to see more rows

the chunk above filters the ADA compliant stations among all distinct
stations. There are 84 ADA compliant stations.

``` r
trans_ent %>% 
  filter(vending == "NO") %>% 
  pull(entry) %>% 
  mean
```

    ## [1] 0.3770492

37.70% of station entrances/exits without vending allow entrance.

## reformat data

to reformat data so that route number and route name are distinct
variables

``` r
trans_ent <- trans_ent %>% 
  pivot_longer(
    route1:route11,
    names_to = "route_number",
    values_to = "route_name")
```

to determine how many distinct stations serve the A train, and of those
how many are ADA compliant:

``` r
trans_ent %>% 
      filter(route_name == "A")  %>% 
      select(station_name, line) %>% 
      distinct
```

    ## # A tibble: 60 × 2
    ##    station_name                  line           
    ##    <chr>                         <chr>          
    ##  1 Times Square                  42nd St Shuttle
    ##  2 125th St                      8 Avenue       
    ##  3 145th St                      8 Avenue       
    ##  4 14th St                       8 Avenue       
    ##  5 168th St - Washington Heights 8 Avenue       
    ##  6 175th St                      8 Avenue       
    ##  7 181st St                      8 Avenue       
    ##  8 190th St                      8 Avenue       
    ##  9 34th St                       8 Avenue       
    ## 10 42nd St                       8 Avenue       
    ## # … with 50 more rows
    ## # ℹ Use `print(n = ...)` to see more rows

``` r
trans_ent %>% 
  filter(route_name == "A", ada == TRUE) %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 17 × 2
    ##    station_name                  line            
    ##    <chr>                         <chr>           
    ##  1 14th St                       8 Avenue        
    ##  2 168th St - Washington Heights 8 Avenue        
    ##  3 175th St                      8 Avenue        
    ##  4 34th St                       8 Avenue        
    ##  5 42nd St                       8 Avenue        
    ##  6 59th St                       8 Avenue        
    ##  7 Inwood - 207th St             8 Avenue        
    ##  8 West 4th St                   8 Avenue        
    ##  9 World Trade Center            8 Avenue        
    ## 10 Times Square-42nd St          Broadway        
    ## 11 59th St-Columbus Circle       Broadway-7th Ave
    ## 12 Times Square                  Broadway-7th Ave
    ## 13 8th Av                        Canarsie        
    ## 14 Franklin Av                   Franklin        
    ## 15 Euclid Av                     Fulton          
    ## 16 Franklin Av                   Fulton          
    ## 17 Howard Beach                  Rockaway

60 distinct stations serve the A train, and of those 17 are ADA
compliant.
